spring:
  datasource:
    url: jdbc:mysql://${db-url}:3306/maplestory?serverTimezone=Asia/Seoul
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
  task:
    scheduling:
      time-zone: Asia/Seoul

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

api:
  key: ${api-key}
